# Generated by Django 4.2 on 2023-05-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_customer',
            new_name='customer',
        ),
    ]
