# Generated by Django 4.2 on 2023-05-19 03:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='SubcontractorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_electrician', models.BooleanField(default=False)),
                ('is_plumber', models.BooleanField(default=False)),
                ('is_carpenter', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUnvan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_unvan_title', models.CharField(max_length=400)),
                ('company_unvan_city', models.CharField(max_length=400)),
                ('company_unvan_state', models.CharField(max_length=400)),
                ('company_unvan_zip', models.CharField(max_length=400)),
                ('company_unvan_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
        ),
    ]
