# Generated by Django 4.2 on 2023-05-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_company_company_email_subcontractorcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_category',
        ),
        migrations.RemoveField(
            model_name='companyunvan',
            name='company',
        ),
        migrations.AddField(
            model_name='companyunvan',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='home.company'),
        ),
    ]
