# Generated by Django 4.2 on 2023-05-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_project_customer_project_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_project_profit',
            new_name='project_profit',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_status',
            new_name='status',
        ),
    ]
