# Generated by Django 4.2 on 2023-05-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_project_project_margin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unvan',
            old_name='unvan_customer',
            new_name='customer',
        ),
    ]
