# Generated by Django 4.2 on 2023-04-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_status_id_for_status_alter_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='id_for_status',
            new_name='for_status',
        ),
    ]
