# Generated by Django 4.2 on 2023-05-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_company_company_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcontractorcategory',
            old_name='is_carpenter',
            new_name='subcontractorcategory_is_carpenter',
        ),
        migrations.RenameField(
            model_name='subcontractorcategory',
            old_name='is_electrician',
            new_name='subcontractorcategory_is_electrician',
        ),
        migrations.RenameField(
            model_name='subcontractorcategory',
            old_name='is_plumber',
            new_name='subcontractorcategory_is_plumber',
        ),
    ]
