# Generated by Django 4.2 on 2023-04-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_id_for_status_status_for_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='for_status',
            new_name='opt_numb',
        ),
    ]
