# Generated by Django 4.2 on 2023-05-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_is_carpenter_subcontractorcategory_subcontractorcategory_is_carpenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractorcategory',
            name='subcontractorcategory_is_carpenter',
        ),
        migrations.RemoveField(
            model_name='subcontractorcategory',
            name='subcontractorcategory_is_electrician',
        ),
        migrations.RemoveField(
            model_name='subcontractorcategory',
            name='subcontractorcategory_is_plumber',
        ),
        migrations.AddField(
            model_name='subcontractorcategory',
            name='subcontractorcategory_title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
