# Generated by Django 4.2 on 2023-05-15 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
