# Generated by Django 4.2 on 2023-05-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_subcontractorcategory_subcontractorcategory_is_carpenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractorcategory',
            name='subcontractorcategory_title',
        ),
        migrations.AddField(
            model_name='subcontractorcategory',
            name='subcontractorcategory_carpenter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcontractorcategory',
            name='subcontractorcategory_electric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcontractorcategory',
            name='subcontractorcategory_plumber',
            field=models.BooleanField(default=False),
        ),
    ]
